@startuml top down Design
component game{

node "model" {
["ai"]--> calculate_best_move
[game logic]--> ValidateMoves
[game logic]--> [player]
[game logic]--> CheckIfWon
}

node "controller" {
[accsess the board]
 [ update the board ]
}
package "view" {
     [ boardGame ]
     [ board ]
     [ background ]
}
}
@enduml
